export enum DocumentType {
  LAB_RESULT = 'LAB_RESULT',
  PRESCRIPTION = 'PRESCRIPTION',
  MEDICAL_RECORD = 'MEDICAL_RECORD',
  INSURANCE_CARD = 'INSURANCE_CARD',
  IMAGING_REPORT = 'IMAGING_REPORT',
  IMMUNIZATION_RECORD = 'IMMUNIZATION_RECORD',
  OTHER = 'OTHER',
}
